/**
 * Plain, structured-clone-safe DTOs for the read-only viewer IPC contract.
 *
 * Everything here is a *value type*: plain objects, arrays, strings, numbers,
 * booleans, and `null`. NO class instances, NO functions, NO `Date` objects —
 * dates are ISO-8601 strings. This guarantees every payload survives Electron's
 * structured-clone IPC boundary unchanged.
 *
 * The renderer is intentionally "dumb": all display formatting (author lists,
 * de-TeXified titles, preview HTML) is done in the **main** process using the
 * core libraries (`@bibdesk/names`, `@bibdesk/tex`, `@bibdesk/model`). These DTOs
 * carry display-ready strings so the renderer just paints them.
 */

/** Opaque id for an open document. Generated by main; used to scope all reads. */
export type DocumentId = string;

/** Opaque stable id for a publication item within a document. */
export type ItemId = string;

// --- Open / close document --------------------------------------------------

/** A single non-fatal issue encountered while parsing a `.bib` file. */
export interface ParseWarning {
  /** `error` for recoverable parse problems; `warning` for advisories. */
  readonly severity: 'error' | 'warning';
  /** Human-readable message (display-ready). */
  readonly message: string;
  /** 1-based source line the issue relates to, if known. */
  readonly line?: number;
}

/** Request payload for opening a document. */
export interface OpenDocumentRequest {
  /** Absolute filesystem path to the `.bib` file. */
  readonly path: string;
}

/**
 * Response/notification payload describing a successfully opened document. Also
 * the body of the {@link IpcEvents.documentOpened} event.
 */
export interface OpenedDocument {
  /** Id to pass to every subsequent read request. */
  readonly documentId: DocumentId;
  /** Resolved absolute path of the opened file. */
  readonly path: string;
  /** Base filename for display (e.g. window title), without directory. */
  readonly displayName: string;
  /** Total number of publications parsed. */
  readonly itemCount: number;
  /** Non-fatal parse issues; empty array when the file parsed cleanly. */
  readonly warnings: readonly ParseWarning[];
  /** Whether the document has unsaved edits (true after undo/redo re-opens it). */
  readonly dirty?: boolean;
}

/** Request payload for closing a document. */
export interface CloseDocumentRequest {
  readonly documentId: DocumentId;
}

/** Notification payload for {@link IpcEvents.documentClosed}. */
export interface ClosedDocument {
  readonly documentId: DocumentId;
}

// --- Open external ----------------------------------------------------------

/** Request to open a URL (browser) or local file (OS default app). */
export interface OpenExternalRequest {
  /** A URL (`http(s)://`, `doi:`/bare DOI handled by main) or a local file path. */
  readonly target: string;
  /** Whether `target` is a remote URL or a local file. */
  readonly kind: 'url' | 'file';
}

/** Result of an open-external request. */
export interface OpenExternalResult {
  readonly ok: boolean;
  /** Failure reason when `ok` is false. */
  readonly error?: string;
}

// --- Editing ----------------------------------------------------------------

/**
 * A single mutation applied to an open document. The renderer sends one of these
 * via `applyEdit`; main mutates the in-memory model and marks the doc dirty.
 * Field `value`s are raw BibTeX field text (not the de-TeXified display form).
 */
export type EditCommand =
  | { readonly kind: 'setField'; readonly itemId: ItemId; readonly field: string; readonly value: string }
  | { readonly kind: 'removeField'; readonly itemId: ItemId; readonly field: string }
  | { readonly kind: 'setCiteKey'; readonly itemId: ItemId; readonly citeKey: string }
  | { readonly kind: 'setType'; readonly itemId: ItemId; readonly entryType: string }
  | { readonly kind: 'generateCiteKey'; readonly itemId: ItemId }
  | { readonly kind: 'addEntry'; readonly entryType: string }
  | { readonly kind: 'duplicateEntry'; readonly itemId: ItemId }
  | { readonly kind: 'deleteEntry'; readonly itemId: ItemId }
  | { readonly kind: 'mergeEntries'; readonly primaryId: ItemId; readonly otherIds: readonly ItemId[] }
  | { readonly kind: 'setMacro'; readonly name: string; readonly value: string }
  | { readonly kind: 'removeMacro'; readonly name: string };

/** Request to apply one {@link EditCommand} to a document. */
export interface ApplyEditRequest {
  readonly documentId: DocumentId;
  readonly command: EditCommand;
}

/** Outcome of an edit: the new dirty state and (when relevant) the affected item. */
export interface EditResult {
  readonly dirty: boolean;
  /** Item the edit focused on (for re-selection); absent for deletes/macros. */
  readonly affectedItemId?: ItemId;
  /** Refreshed detail of the affected item, when one applies. */
  readonly detail?: ItemDetail;
}

/** A document-level `@string` macro definition. */
export interface MacroDef {
  readonly name: string;
  /** Raw BibTeX value text (literal or `a # b` concatenation). */
  readonly value: string;
}

/** Request to list a document's `@string` macros. */
export interface ListMacrosRequest {
  readonly documentId: DocumentId;
}

/** A document's file-level macros, in dependency order. */
export interface ListMacrosResponse {
  readonly macros: readonly MacroDef[];
}

/** Request to save a document (optionally to a new path = Save As). */
export interface SaveDocumentRequest {
  readonly documentId: DocumentId;
  readonly targetPath?: string;
}

/** Result of a save: where it was written. */
export interface SaveDocumentResult {
  readonly documentId: DocumentId;
  readonly path: string;
}

// --- Formatted citations (CSL) ----------------------------------------------

/** A selectable CSL citation style. */
export interface CitationStyle {
  readonly id: string;
  readonly label: string;
}

/** The CSL styles the app offers (bundled offline by citation-js plugin-csl). */
export const CITATION_STYLES: readonly CitationStyle[] = [
  { id: 'apa', label: 'APA' },
  { id: 'vancouver', label: 'Vancouver' },
  { id: 'harvard1', label: 'Harvard' },
];

/** Request to format one item as a styled citation. */
export interface FormatCitationRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
  /** CSL style id from {@link CITATION_STYLES}. */
  readonly styleId: string;
}

/** Result: the formatted citation as an HTML string. */
export interface FormatCitationResult {
  readonly styleId: string;
  /** Formatted bibliography entry (HTML); empty when formatting failed. */
  readonly html: string;
  /** Failure reason when `html` is empty. */
  readonly error?: string;
}

// --- List publications ------------------------------------------------------

/** Sort direction for a publications listing. */
export type SortDirection = 'asc' | 'desc';

/**
 * Sort spec for a publications listing. `key` is a {@link PublicationRow} column
 * key (or any BibTeX field name the main process knows how to sort by); main
 * does the actual sorting using the core comparators.
 */
export interface SortSpec {
  readonly key: string;
  readonly direction: SortDirection;
}

/** Request payload for a page/range of publications. */
export interface ListPublicationsRequest {
  readonly documentId: DocumentId;
  /** 0-based index of the first row to return. */
  readonly offset: number;
  /** Maximum number of rows to return. */
  readonly limit: number;
  /** Optional sort; main applies a default (cite key asc) when omitted. */
  readonly sort?: SortSpec;
  /** When present, restrict rows to members of this group (see {@link GroupNode}). */
  readonly groupId?: string;
  /** Extra (non-builtin) field names to include in each row's `extra` map. */
  readonly extraFields?: readonly string[];
}

/**
 * Thin row view-model for the virtualized publications table. Every field is a
 * display-ready string: `authorsDisplay` is already formatted (via the name
 * formatter) and `title` is already de-TeXified for display. The renderer never
 * re-formats these.
 */
export interface PublicationRow {
  /** Stable item id (row key + the id to pass to {@link GetItemDetailRequest}). */
  readonly id: ItemId;
  /** Cite key column. */
  readonly citeKey: string;
  /** BibTeX entry type, lowercased (e.g. `article`, `book`). */
  readonly type: string;
  /** Authors column — pre-formatted display string (may be empty). */
  readonly authorsDisplay: string;
  /** Title column — de-TeXified for display (may be empty). */
  readonly title: string;
  /** Year column — display string (may be empty when absent/unparseable). */
  readonly year: string;
  /** True when the entry has a non-empty `Keywords` field (key-icon column). */
  readonly hasKeywords: boolean;
  /** Number of local file attachments (`Bdsk-File-N` + `Local-Url`); paperclip column. */
  readonly attachmentCount: number;
  /** Tri-state of the `Read` boolean field: 1 on, -1 off, 0 unset (checkbox column). */
  readonly read: -1 | 0 | 1;
  /** Rating field value 0–5, or 0 when absent (star column). */
  readonly rating: number;
  /** Display values for any user-configured extra-field columns (de-TeXified). */
  readonly extra?: Readonly<Record<string, string>>;
}

/** Response payload for a publications listing. */
export interface ListPublicationsResponse {
  /** The requested window of rows. */
  readonly rows: readonly PublicationRow[];
  /** Total number of rows in the (filtered) result set, for the virtualizer. */
  readonly total: number;
}

// --- List groups ------------------------------------------------------------

/**
 * Kind of group, mirroring BibDesk's taxonomy (subsystem-04). `library` is the
 * whole library; `static`/`smart` are user groups; `category`/`author` are
 * auto-generated field groups (author = person category field); `url`/`script`
 * are external groups. Read-only viewer renders all of them; only membership is
 * exercised.
 */
export type GroupKind =
  | 'library'
  | 'static'
  | 'smart'
  | 'category'
  | 'author'
  | 'url'
  | 'script';

/** Request payload for the groups sidebar tree. */
export interface ListGroupsRequest {
  readonly documentId: DocumentId;
}

/**
 * One node in the groups sidebar. The tree is reconstructed from `parentId`
 * (root parents have no `parentId`); BibDesk's tree is at most two levels deep.
 */
export interface GroupNode {
  /** Stable group id (pass as {@link ListPublicationsRequest.groupId}). */
  readonly id: string;
  /** Group kind — drives the sidebar icon. */
  readonly kind: GroupKind;
  /** Display name (de-TeXified / formatted by main as appropriate). */
  readonly name: string;
  /** Number of publications in the group (`library` = whole library size). */
  readonly count: number;
  /** Parent group id; absent for the fixed root parent groups. */
  readonly parentId?: string;
}

/** Response payload for the groups sidebar — a flat list joined via `parentId`. */
export interface ListGroupsResponse {
  readonly groups: readonly GroupNode[];
}

// --- Item detail ------------------------------------------------------------

/** Request payload for one item's full detail. */
export interface GetItemDetailRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
}

/** One field row in the detail view (display value, not raw BibTeX). */
export interface ItemField {
  /** Canonical field name (e.g. `Author`, `Title`, `Journal`). */
  readonly name: string;
  /** Display-ready value (macros expanded, de-TeXified by main). */
  readonly value: string;
  /** Raw BibTeX field text for editing (not de-TeXified / not brace-stripped). */
  readonly rawValue: string;
  /** True when the value is inherited from a crossref parent rather than set locally. */
  readonly isInherited: boolean;
}

/** One attachment (linked file or remote URL) in the detail view. */
export interface ItemFile {
  /** `file` for a local file, `url` for a remote URL. */
  readonly kind: 'file' | 'url';
  /** Display name (basename for files, label/host for URLs). */
  readonly displayName: string;
  /** Resolved URL string (`file://...`/absolute path for local files, absolute URL otherwise). */
  readonly url: string;
  /**
   * Source `Bdsk-File-N` field name when this attachment is a removable managed
   * file link. Absent for attachments synthesised from `Url`/`Local-Url` fields.
   */
  readonly field?: string;
}

/** Request to add attachment(s) to an item (main opens a file picker). */
export interface AddAttachmentRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
}

/** Request to remove one managed attachment (`Bdsk-File-N`) from an item. */
export interface RemoveAttachmentRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
  readonly field: string;
}

/** Request to read an attachment's bytes (e.g. to preview a PDF in-app). */
export interface ReadAttachmentRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
  /** The attachment's resolved url/path (from {@link ItemFile.url}). */
  readonly url: string;
}

/** Bytes of an attachment, or an error. `data` is structured-clone-safe. */
export interface ReadAttachmentResponse {
  readonly data: Uint8Array | null;
  readonly error?: string;
}

// --- Export -----------------------------------------------------------------

/**
 * Output format for {@link ExportTextRequest}. `bibtex` is implemented today
 * (reuses the round-trip serializer); the others are reserved for the export
 * feature and may be rejected with an error until then.
 */
export type ExportFormat = 'bibtex' | 'ris' | 'csv' | 'html' | 'rtf';

/** Request serialized text for a whole document, or a subset of its items. */
export interface ExportTextRequest {
  readonly documentId: DocumentId;
  readonly format: ExportFormat;
  /** When present, export only these items (in this order); else the whole library. */
  readonly itemIds?: readonly ItemId[];
}

/** Serialized text in the requested format, or an error if unsupported. */
export interface ExportTextResponse {
  readonly text: string;
  readonly error?: string;
}

// --- Online search / import -------------------------------------------------

/** An online bibliographic source. */
export type OnlineSource = 'crossref' | 'arxiv';

/** The online sources the app offers. */
export const ONLINE_SOURCES: readonly { id: OnlineSource; label: string }[] = [
  { id: 'crossref', label: 'CrossRef' },
  { id: 'arxiv', label: 'arXiv' },
];

/** One normalised online search result (display fields + BibTeX fields to import). */
export interface OnlineResult {
  readonly source: OnlineSource;
  /** Suggested BibTeX entry type (e.g. `article`). */
  readonly entryType: string;
  readonly title: string;
  /** Display author list. */
  readonly authorsDisplay: string;
  readonly year: string;
  readonly venue?: string;
  readonly doi?: string;
  readonly url?: string;
  /** Canonical BibTeX fields used when importing this result as a new entry. */
  readonly fields: Readonly<Record<string, string>>;
}

/** Request to search an online source. */
export interface SearchOnlineRequest {
  readonly source: OnlineSource;
  readonly query: string;
}

/** Online search results (or an error message). */
export interface SearchOnlineResponse {
  readonly results: readonly OnlineResult[];
  readonly error?: string;
}

/** Request to import one online result into a document as a new entry. */
export interface ImportOnlineRequest {
  readonly documentId: DocumentId;
  readonly result: OnlineResult;
}

// --- Paste / drag-and-drop import -------------------------------------------

/** Paste BibTeX text into a document (e.g. an entry copied from Google Scholar). */
export interface PasteEntriesRequest {
  readonly documentId: DocumentId;
  /** Raw BibTeX text containing one or more `@type{…}` entries. */
  readonly text: string;
}

/** Import dropped files into a document: `.bib` merge, other files → entry+attach. */
export interface ImportFilesRequest {
  readonly documentId: DocumentId;
  /** Absolute file paths (from the renderer's drop handler). */
  readonly paths: readonly string[];
}

/** Open a file picker (in main) and import the chosen `.bib`/`.ris`/other files. */
export interface ImportDialogRequest {
  readonly documentId: DocumentId;
}

/** Outcome of a paste/file import: the new item ids and any non-fatal warnings. */
export interface ImportResult {
  readonly dirty: boolean;
  /** Ids of the newly added entries (for selection); empty when nothing imported. */
  readonly addedIds: readonly ItemId[];
  /** Non-fatal messages (e.g. "no entries found", per-file read errors). */
  readonly warnings: readonly string[];
}

// --- Find & Replace ---------------------------------------------------------

/** A find/replace operation over field values (preview when `apply` is false). */
export interface FindReplaceRequest {
  readonly documentId: DocumentId;
  /** Restrict to one field name, or undefined to search every field. */
  readonly field?: string;
  readonly find: string;
  readonly replace: string;
  /** Treat `find` as a JS regular expression. */
  readonly regex: boolean;
  readonly caseSensitive: boolean;
  /** When true, perform the replacement; when false, only report matches. */
  readonly apply: boolean;
  /** Restrict the scope to a group's members (optional). */
  readonly groupId?: string;
}

/** One field that matched (with the would-be/after value). */
export interface FindReplaceMatch {
  readonly itemId: ItemId;
  readonly citeKey: string;
  readonly field: string;
  readonly before: string;
  readonly after: string;
  /** Number of occurrences in this field. */
  readonly count: number;
}

/** Outcome of a find/replace: per-field matches and the running totals. */
export interface FindReplaceResult {
  readonly matches: readonly FindReplaceMatch[];
  /** Total number of occurrences across all matched fields. */
  readonly total: number;
  readonly applied: boolean;
  readonly dirty: boolean;
  /** Set when `find` is an invalid regular expression. */
  readonly error?: string;
}

// --- Group editor -----------------------------------------------------------

/** One smart-group condition (BibDesk BDSKCondition). */
export interface SmartCondition {
  readonly key: string;
  /** BDSKQueryOperator integer (e.g. contains/equals/starts-with). */
  readonly comparison: number;
  readonly value: string;
}

/** A mutation of the document's groups (create/rename/delete/membership). */
export type GroupCommand =
  | { readonly kind: 'createStatic'; readonly name: string; readonly citeKeys?: readonly string[] }
  | {
      readonly kind: 'createSmart';
      readonly name: string;
      readonly conditions: readonly SmartCondition[];
      /** 0 = all conditions (AND), 1 = any (OR). */
      readonly conjunction: 0 | 1;
    }
  | { readonly kind: 'rename'; readonly groupId: string; readonly name: string }
  | { readonly kind: 'delete'; readonly groupId: string }
  | {
      readonly kind: 'setMembers';
      readonly groupId: string;
      readonly citeKeys: readonly string[];
      /** true = add to the static group, false = remove. */
      readonly add: boolean;
    };

/** Request to apply one {@link GroupCommand}. */
export interface GroupEditRequest {
  readonly documentId: DocumentId;
  readonly command: GroupCommand;
}

/** Outcome of a group edit: new dirty state + the affected/created group id. */
export interface GroupEditResult {
  readonly dirty: boolean;
  readonly groupId?: string;
}

// --- Claude assistant -------------------------------------------------------

/** Whether the user's Anthropic API key is stored (via Electron safeStorage). */
export interface AgentKeyStatus {
  readonly hasKey: boolean;
  /** True if OS-level encryption is available for storing the key. */
  readonly encryptionAvailable: boolean;
}

/** Store (or, with an empty string, clear) the Anthropic API key. */
export interface AgentSetKeyRequest {
  readonly key: string;
}

/** Send one user message to the assistant for the open document. */
export interface AgentRunRequest {
  readonly documentId: DocumentId;
  readonly message: string;
}

/** The assistant's reply for one turn. */
export interface AgentRunResponse {
  readonly reply: string;
  /** Human-readable log of tool calls made this turn. */
  readonly toolLog: readonly string[];
  /** True if an approved mutation ran (the renderer should reload). */
  readonly mutated: boolean;
  readonly error?: string;
}

// --- AutoFile ---------------------------------------------------------------

/** AutoFile an item's managed attachments into the Papers folder. */
export interface AutoFileRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
}

/** Result of an AutoFile: how many files moved, per-file errors, refreshed detail. */
export interface AutoFileResult {
  readonly moved: number;
  readonly errors: readonly string[];
  readonly dirty: boolean;
  readonly detail: ItemDetail;
}

/** Response from the folder picker (null when cancelled). */
export interface ChooseFolderResponse {
  readonly path: string | null;
}

// --- Field-value autocomplete -----------------------------------------------

/** Request distinct existing values for a field (for editor autocomplete). */
export interface FieldSuggestionsRequest {
  readonly documentId: DocumentId;
  readonly field: string;
}

/** Distinct values (deduped, sorted, capped) seen in the library for a field. */
export interface FieldSuggestionsResponse {
  readonly values: readonly string[];
}

// --- Find Duplicates --------------------------------------------------------

/** Request a duplicate scan of a document. */
export interface FindDuplicatesRequest {
  readonly documentId: DocumentId;
}

/** One entry within a duplicate group (light display info for the picker). */
export interface DuplicateEntry {
  readonly id: ItemId;
  readonly citeKey: string;
  readonly title: string;
}

/** A set of entries considered duplicates of one another. */
export interface DuplicateGroup {
  /** `citeKey` = identical cite keys; `content` = equivalent field content. */
  readonly kind: 'citeKey' | 'content';
  readonly entries: readonly DuplicateEntry[];
}

/** Result of a duplicate scan over a document. */
export interface FindDuplicatesResult {
  readonly groups: readonly DuplicateGroup[];
  /** Total number of entries involved in any duplicate group. */
  readonly total: number;
}

// --- Full-text search (SQLite FTS5) -----------------------------------------

/** Request a full-text search over a document. */
export interface FtsSearchRequest {
  readonly documentId: DocumentId;
  readonly query: string;
}

/** Full-text search results: matching item ids, best-match first. */
export interface FtsSearchResponse {
  /** False if the native FTS index is unavailable (caller should fall back). */
  readonly available: boolean;
  readonly ids: readonly ItemId[];
}

// --- Preferences ------------------------------------------------------------

/** User-overridable field-type classification sets (BibDesk's field-type prefs). */
export interface FieldTypeSettings {
  /** Fields holding people (parsed as authors). */
  readonly person: readonly string[];
  /** Local file-path fields. */
  readonly localFile: readonly string[];
  /** Remote URL fields. */
  readonly remoteURL: readonly string[];
  /** Star-rating (0–5) fields. */
  readonly rating: readonly string[];
  /** Boolean (checkbox) fields. */
  readonly boolean: readonly string[];
  /** Tri-state fields. */
  readonly triState: readonly string[];
  /** Citation (cite-key list) fields. */
  readonly citation: readonly string[];
}

/** Application preferences (persisted; the BibDesk-equivalent options this app has). */
export interface Settings {
  /** UI theme. `system` follows the OS appearance. */
  readonly theme: 'light' | 'dark' | 'system';
  /** Default CSL style id for the citation preview (from {@link CITATION_STYLES}). */
  readonly defaultCiteStyle: string;
  /** Cite-key generation format (BDSKFormatParser mini-language, e.g. `%a1:%Y%u2`). */
  readonly citeKeyFormat: string;
  /** Entry type used by the toolbar **New** button. */
  readonly defaultEntryType: string;
  /**
   * Template inserted when dragging rows to a TeX editor or copying `\cite{}`.
   * `%K` expands to the comma-joined cite key(s); e.g. `\cite{%K}`, `\citep{%K}`.
   */
  readonly citeCommandTemplate: string;
  /**
   * Ordered list of table column keys. Builtin keys: `citeKey`, `type`, `authors`,
   * `title`, `year`, `keywords`, `attachments`, `read`, `rating`. Any other key is
   * treated as a BibTeX field name and shown as a text column.
   */
  readonly columns: readonly string[];
  /** Absolute path of the AutoFile "Papers" folder (empty = AutoFile disabled). */
  readonly papersFolder: string;
  /** AutoFile destination-name format (BDSKFormatParser; e.g. `%a1/%Y%u0`). */
  readonly autoFileFormat: string;
  /** When true, save automatically a moment after each edit. */
  readonly autosave: boolean;
  /** Anthropic model id for the Claude assistant (e.g. `claude-opus-4-8`). */
  readonly agentModel: string;
  /** Field-type classification overrides. */
  readonly fieldTypes: FieldTypeSettings;
}

/** Builtin (non-field) table column keys. */
export const BUILTIN_COLUMNS = [
  'citeKey',
  'type',
  'authors',
  'title',
  'year',
  'keywords',
  'attachments',
  'read',
  'rating',
] as const;

/** Factory-default preferences (mirror the bundled BibDesk defaults). */
export const DEFAULT_SETTINGS: Settings = {
  theme: 'system',
  defaultCiteStyle: 'apa',
  citeKeyFormat: '%a1:%Y%u2',
  defaultEntryType: 'article',
  citeCommandTemplate: '\\cite{%K}',
  columns: ['citeKey', 'type', 'authors', 'title', 'year', 'keywords', 'attachments', 'read'],
  papersFolder: '',
  autoFileFormat: '%a1/%Y%u0',
  autosave: false,
  agentModel: 'claude-opus-4-8',
  fieldTypes: {
    person: ['Author', 'Editor'],
    localFile: ['Local-Url'],
    remoteURL: ['Url', 'Doi', 'Citeseerurl'],
    rating: ['Rating'],
    boolean: ['Read'],
    triState: [],
    citation: ['Cited-By', 'Cites'],
  },
};

/** Request to read the current settings (no payload). */
export type GetSettingsRequest = Readonly<Record<string, never>>;

/** Request to update settings: a partial patch merged over the current values. */
export interface UpdateSettingsRequest {
  readonly patch: Partial<Settings>;
}

/**
 * Full detail of one publication for the detail/preview pane. `fields` are the
 * display field rows, `files` the attachments, and `previewHtml` an optional
 * pre-rendered HTML snippet for the preview card (rendered by main from a
 * template). The renderer treats `previewHtml` as trusted-but-sanitized content.
 */
export interface ItemDetail {
  readonly id: ItemId;
  readonly citeKey: string;
  /** BibTeX entry type, lowercased. */
  readonly type: string;
  readonly fields: readonly ItemField[];
  readonly files: readonly ItemFile[];
  /** Optional pre-rendered HTML for the preview card. */
  readonly previewHtml?: string;
  /** Raw markdown notes (the `Annote` field) for the notes editor. */
  readonly notesRaw: string;
  /** Rendered notes HTML (markdown + `[[citeKey]]` cross-references). */
  readonly notesHtml: string;
}

// --- Menu commands ----------------------------------------------------------

/**
 * A renderer-side action triggered from the native application menu. Main owns
 * the menu (an Electron requirement) but most items act on renderer/store state
 * (selection, modals, theme), so it forwards them as one of these commands via
 * the {@link IpcEvents.menuCommand} event; the renderer dispatches to the store.
 *
 * File-level actions that main can do itself (Open, Save, Save As, Revert,
 * Export to a file) are handled in main directly and are NOT in this union.
 */
export type MenuCommand =
  // Publication
  | 'newPublication'
  | 'pastePublication'
  | 'importFile'
  | 'duplicate'
  | 'delete'
  | 'generateCiteKey'
  | 'addAttachment'
  | 'autoFile'
  | 'online'
  | 'editMacros'
  | 'findDuplicates'
  | 'assistant'
  // Edit / clipboard (operate on the selection)
  | 'find'
  | 'findReplace'
  | 'copyCiteKey'
  | 'copyCitation'
  | 'copyBibtex'
  | 'copyCite'
  // View
  | 'toggleTheme'
  // App
  | 'save';
