/**
 * Plain, structured-clone-safe DTOs for the read-only viewer IPC contract.
 *
 * Everything here is a *value type*: plain objects, arrays, strings, numbers,
 * booleans, and `null`. NO class instances, NO functions, NO `Date` objects —
 * dates are ISO-8601 strings. This guarantees every payload survives Electron's
 * structured-clone IPC boundary unchanged.
 *
 * The renderer is intentionally "dumb": all display formatting (author lists,
 * de-TeXified titles, preview HTML) is done in the **main** process using the
 * core libraries (`@bibdesk/names`, `@bibdesk/tex`, `@bibdesk/model`). These DTOs
 * carry display-ready strings so the renderer just paints them.
 */

/** Opaque id for an open document. Generated by main; used to scope all reads. */
export type DocumentId = string;

/** Opaque stable id for a publication item within a document. */
export type ItemId = string;

// --- Open / close document --------------------------------------------------

/** A single non-fatal issue encountered while parsing a `.bib` file. */
export interface ParseWarning {
  /** `error` for recoverable parse problems; `warning` for advisories. */
  readonly severity: 'error' | 'warning';
  /** Human-readable message (display-ready). */
  readonly message: string;
  /** 1-based source line the issue relates to, if known. */
  readonly line?: number;
}

/** Request payload for opening a document. */
export interface OpenDocumentRequest {
  /** Absolute filesystem path to the `.bib` file. */
  readonly path: string;
}

/**
 * Response/notification payload describing a successfully opened document. Also
 * the body of the {@link IpcEvents.documentOpened} event.
 */
export interface OpenedDocument {
  /** Id to pass to every subsequent read request. */
  readonly documentId: DocumentId;
  /** Resolved absolute path of the opened file. */
  readonly path: string;
  /** Base filename for display (e.g. window title), without directory. */
  readonly displayName: string;
  /** Total number of publications parsed. */
  readonly itemCount: number;
  /** Non-fatal parse issues; empty array when the file parsed cleanly. */
  readonly warnings: readonly ParseWarning[];
}

/** Request payload for closing a document. */
export interface CloseDocumentRequest {
  readonly documentId: DocumentId;
}

/** Notification payload for {@link IpcEvents.documentClosed}. */
export interface ClosedDocument {
  readonly documentId: DocumentId;
}

// --- Open external ----------------------------------------------------------

/** Request to open a URL (browser) or local file (OS default app). */
export interface OpenExternalRequest {
  /** A URL (`http(s)://`, `doi:`/bare DOI handled by main) or a local file path. */
  readonly target: string;
  /** Whether `target` is a remote URL or a local file. */
  readonly kind: 'url' | 'file';
}

/** Result of an open-external request. */
export interface OpenExternalResult {
  readonly ok: boolean;
  /** Failure reason when `ok` is false. */
  readonly error?: string;
}

// --- Editing ----------------------------------------------------------------

/**
 * A single mutation applied to an open document. The renderer sends one of these
 * via `applyEdit`; main mutates the in-memory model and marks the doc dirty.
 * Field `value`s are raw BibTeX field text (not the de-TeXified display form).
 */
export type EditCommand =
  | { readonly kind: 'setField'; readonly itemId: ItemId; readonly field: string; readonly value: string }
  | { readonly kind: 'removeField'; readonly itemId: ItemId; readonly field: string }
  | { readonly kind: 'setCiteKey'; readonly itemId: ItemId; readonly citeKey: string }
  | { readonly kind: 'setType'; readonly itemId: ItemId; readonly entryType: string }
  | { readonly kind: 'generateCiteKey'; readonly itemId: ItemId }
  | { readonly kind: 'addEntry'; readonly entryType: string }
  | { readonly kind: 'duplicateEntry'; readonly itemId: ItemId }
  | { readonly kind: 'deleteEntry'; readonly itemId: ItemId }
  | { readonly kind: 'setMacro'; readonly name: string; readonly value: string }
  | { readonly kind: 'removeMacro'; readonly name: string };

/** Request to apply one {@link EditCommand} to a document. */
export interface ApplyEditRequest {
  readonly documentId: DocumentId;
  readonly command: EditCommand;
}

/** Outcome of an edit: the new dirty state and (when relevant) the affected item. */
export interface EditResult {
  readonly dirty: boolean;
  /** Item the edit focused on (for re-selection); absent for deletes/macros. */
  readonly affectedItemId?: ItemId;
  /** Refreshed detail of the affected item, when one applies. */
  readonly detail?: ItemDetail;
}

/** A document-level `@string` macro definition. */
export interface MacroDef {
  readonly name: string;
  /** Raw BibTeX value text (literal or `a # b` concatenation). */
  readonly value: string;
}

/** Request to list a document's `@string` macros. */
export interface ListMacrosRequest {
  readonly documentId: DocumentId;
}

/** A document's file-level macros, in dependency order. */
export interface ListMacrosResponse {
  readonly macros: readonly MacroDef[];
}

/** Request to save a document (optionally to a new path = Save As). */
export interface SaveDocumentRequest {
  readonly documentId: DocumentId;
  readonly targetPath?: string;
}

/** Result of a save: where it was written. */
export interface SaveDocumentResult {
  readonly documentId: DocumentId;
  readonly path: string;
}

// --- Formatted citations (CSL) ----------------------------------------------

/** A selectable CSL citation style. */
export interface CitationStyle {
  readonly id: string;
  readonly label: string;
}

/** The CSL styles the app offers (bundled offline by citation-js plugin-csl). */
export const CITATION_STYLES: readonly CitationStyle[] = [
  { id: 'apa', label: 'APA' },
  { id: 'vancouver', label: 'Vancouver' },
  { id: 'harvard1', label: 'Harvard' },
];

/** Request to format one item as a styled citation. */
export interface FormatCitationRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
  /** CSL style id from {@link CITATION_STYLES}. */
  readonly styleId: string;
}

/** Result: the formatted citation as an HTML string. */
export interface FormatCitationResult {
  readonly styleId: string;
  /** Formatted bibliography entry (HTML); empty when formatting failed. */
  readonly html: string;
  /** Failure reason when `html` is empty. */
  readonly error?: string;
}

// --- List publications ------------------------------------------------------

/** Sort direction for a publications listing. */
export type SortDirection = 'asc' | 'desc';

/**
 * Sort spec for a publications listing. `key` is a {@link PublicationRow} column
 * key (or any BibTeX field name the main process knows how to sort by); main
 * does the actual sorting using the core comparators.
 */
export interface SortSpec {
  readonly key: string;
  readonly direction: SortDirection;
}

/** Request payload for a page/range of publications. */
export interface ListPublicationsRequest {
  readonly documentId: DocumentId;
  /** 0-based index of the first row to return. */
  readonly offset: number;
  /** Maximum number of rows to return. */
  readonly limit: number;
  /** Optional sort; main applies a default (cite key asc) when omitted. */
  readonly sort?: SortSpec;
  /** When present, restrict rows to members of this group (see {@link GroupNode}). */
  readonly groupId?: string;
}

/**
 * Thin row view-model for the virtualized publications table. Every field is a
 * display-ready string: `authorsDisplay` is already formatted (via the name
 * formatter) and `title` is already de-TeXified for display. The renderer never
 * re-formats these.
 */
export interface PublicationRow {
  /** Stable item id (row key + the id to pass to {@link GetItemDetailRequest}). */
  readonly id: ItemId;
  /** Cite key column. */
  readonly citeKey: string;
  /** BibTeX entry type, lowercased (e.g. `article`, `book`). */
  readonly type: string;
  /** Authors column — pre-formatted display string (may be empty). */
  readonly authorsDisplay: string;
  /** Title column — de-TeXified for display (may be empty). */
  readonly title: string;
  /** Year column — display string (may be empty when absent/unparseable). */
  readonly year: string;
}

/** Response payload for a publications listing. */
export interface ListPublicationsResponse {
  /** The requested window of rows. */
  readonly rows: readonly PublicationRow[];
  /** Total number of rows in the (filtered) result set, for the virtualizer. */
  readonly total: number;
}

// --- List groups ------------------------------------------------------------

/**
 * Kind of group, mirroring BibDesk's taxonomy (subsystem-04). `library` is the
 * whole library; `static`/`smart` are user groups; `category`/`author` are
 * auto-generated field groups (author = person category field); `url`/`script`
 * are external groups. Read-only viewer renders all of them; only membership is
 * exercised.
 */
export type GroupKind =
  | 'library'
  | 'static'
  | 'smart'
  | 'category'
  | 'author'
  | 'url'
  | 'script';

/** Request payload for the groups sidebar tree. */
export interface ListGroupsRequest {
  readonly documentId: DocumentId;
}

/**
 * One node in the groups sidebar. The tree is reconstructed from `parentId`
 * (root parents have no `parentId`); BibDesk's tree is at most two levels deep.
 */
export interface GroupNode {
  /** Stable group id (pass as {@link ListPublicationsRequest.groupId}). */
  readonly id: string;
  /** Group kind — drives the sidebar icon. */
  readonly kind: GroupKind;
  /** Display name (de-TeXified / formatted by main as appropriate). */
  readonly name: string;
  /** Number of publications in the group (`library` = whole library size). */
  readonly count: number;
  /** Parent group id; absent for the fixed root parent groups. */
  readonly parentId?: string;
}

/** Response payload for the groups sidebar — a flat list joined via `parentId`. */
export interface ListGroupsResponse {
  readonly groups: readonly GroupNode[];
}

// --- Item detail ------------------------------------------------------------

/** Request payload for one item's full detail. */
export interface GetItemDetailRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
}

/** One field row in the detail view (display value, not raw BibTeX). */
export interface ItemField {
  /** Canonical field name (e.g. `Author`, `Title`, `Journal`). */
  readonly name: string;
  /** Display-ready value (macros expanded, de-TeXified by main). */
  readonly value: string;
  /** Raw BibTeX field text for editing (not de-TeXified / not brace-stripped). */
  readonly rawValue: string;
  /** True when the value is inherited from a crossref parent rather than set locally. */
  readonly isInherited: boolean;
}

/** One attachment (linked file or remote URL) in the detail view. */
export interface ItemFile {
  /** `file` for a local file, `url` for a remote URL. */
  readonly kind: 'file' | 'url';
  /** Display name (basename for files, label/host for URLs). */
  readonly displayName: string;
  /** Resolved URL string (`file://...`/absolute path for local files, absolute URL otherwise). */
  readonly url: string;
  /**
   * Source `Bdsk-File-N` field name when this attachment is a removable managed
   * file link. Absent for attachments synthesised from `Url`/`Local-Url` fields.
   */
  readonly field?: string;
}

/** Request to add attachment(s) to an item (main opens a file picker). */
export interface AddAttachmentRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
}

/** Request to remove one managed attachment (`Bdsk-File-N`) from an item. */
export interface RemoveAttachmentRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
  readonly field: string;
}

// --- Online search / import -------------------------------------------------

/** An online bibliographic source. */
export type OnlineSource = 'crossref' | 'arxiv';

/** The online sources the app offers. */
export const ONLINE_SOURCES: readonly { id: OnlineSource; label: string }[] = [
  { id: 'crossref', label: 'CrossRef' },
  { id: 'arxiv', label: 'arXiv' },
];

/** One normalised online search result (display fields + BibTeX fields to import). */
export interface OnlineResult {
  readonly source: OnlineSource;
  /** Suggested BibTeX entry type (e.g. `article`). */
  readonly entryType: string;
  readonly title: string;
  /** Display author list. */
  readonly authorsDisplay: string;
  readonly year: string;
  readonly venue?: string;
  readonly doi?: string;
  readonly url?: string;
  /** Canonical BibTeX fields used when importing this result as a new entry. */
  readonly fields: Readonly<Record<string, string>>;
}

/** Request to search an online source. */
export interface SearchOnlineRequest {
  readonly source: OnlineSource;
  readonly query: string;
}

/** Online search results (or an error message). */
export interface SearchOnlineResponse {
  readonly results: readonly OnlineResult[];
  readonly error?: string;
}

/** Request to import one online result into a document as a new entry. */
export interface ImportOnlineRequest {
  readonly documentId: DocumentId;
  readonly result: OnlineResult;
}

/**
 * Full detail of one publication for the detail/preview pane. `fields` are the
 * display field rows, `files` the attachments, and `previewHtml` an optional
 * pre-rendered HTML snippet for the preview card (rendered by main from a
 * template). The renderer treats `previewHtml` as trusted-but-sanitized content.
 */
export interface ItemDetail {
  readonly id: ItemId;
  readonly citeKey: string;
  /** BibTeX entry type, lowercased. */
  readonly type: string;
  readonly fields: readonly ItemField[];
  readonly files: readonly ItemFile[];
  /** Optional pre-rendered HTML for the preview card. */
  readonly previewHtml?: string;
  /** Raw markdown notes (the `Annote` field) for the notes editor. */
  readonly notesRaw: string;
  /** Rendered notes HTML (markdown + `[[citeKey]]` cross-references). */
  readonly notesHtml: string;
}
