/**
 * Plain, structured-clone-safe DTOs for the read-only viewer IPC contract.
 *
 * Everything here is a *value type*: plain objects, arrays, strings, numbers,
 * booleans, and `null`. NO class instances, NO functions, NO `Date` objects —
 * dates are ISO-8601 strings. This guarantees every payload survives Electron's
 * structured-clone IPC boundary unchanged.
 *
 * The renderer is intentionally "dumb": all display formatting (author lists,
 * de-TeXified titles, preview HTML) is done in the **main** process using the
 * core libraries (`@bibdesk/names`, `@bibdesk/tex`, `@bibdesk/model`). These DTOs
 * carry display-ready strings so the renderer just paints them.
 */

/** Opaque id for an open document. Generated by main; used to scope all reads. */
export type DocumentId = string;

/** Opaque stable id for a publication item within a document. */
export type ItemId = string;

// --- Open / close document --------------------------------------------------

/** A single non-fatal issue encountered while parsing a `.bib` file. */
export interface ParseWarning {
  /** `error` for recoverable parse problems; `warning` for advisories. */
  readonly severity: 'error' | 'warning';
  /** Human-readable message (display-ready). */
  readonly message: string;
  /** 1-based source line the issue relates to, if known. */
  readonly line?: number;
}

/** Request payload for opening a document. */
export interface OpenDocumentRequest {
  /** Absolute filesystem path to the `.bib` file. */
  readonly path: string;
}

/**
 * Response/notification payload describing a successfully opened document. Also
 * the body of the {@link IpcEvents.documentOpened} event.
 */
export interface OpenedDocument {
  /** Id to pass to every subsequent read request. */
  readonly documentId: DocumentId;
  /** Resolved absolute path of the opened file. */
  readonly path: string;
  /** Base filename for display (e.g. window title), without directory. */
  readonly displayName: string;
  /** Total number of publications parsed. */
  readonly itemCount: number;
  /** Non-fatal parse issues; empty array when the file parsed cleanly. */
  readonly warnings: readonly ParseWarning[];
  /** Whether the document has unsaved edits (true after undo/redo re-opens it). */
  readonly dirty?: boolean;
  /**
   * The file's detected text encoding (id, e.g. `utf8`, `windows-1252`, `macintosh`).
   * The file is read and written in this encoding (see File → Text Encoding).
   */
  readonly encoding: string;
}

/** Request payload for closing a document. */
export interface CloseDocumentRequest {
  readonly documentId: DocumentId;
}

/** Notification payload for {@link IpcEvents.documentClosed}. */
export interface ClosedDocument {
  readonly documentId: DocumentId;
}

// --- Open external ----------------------------------------------------------

/** Request to open a URL (browser) or local file (OS default app). */
export interface OpenExternalRequest {
  /** A URL (`http(s)://`, `doi:`/bare DOI handled by main) or a local file path. */
  readonly target: string;
  /** Whether `target` is a remote URL or a local file. */
  readonly kind: 'url' | 'file';
}

/** Result of an open-external request. */
export interface OpenExternalResult {
  readonly ok: boolean;
  /** Failure reason when `ok` is false. */
  readonly error?: string;
}

// --- Editing ----------------------------------------------------------------

/**
 * A single mutation applied to an open document. The renderer sends one of these
 * via `applyEdit`; main mutates the in-memory model and marks the doc dirty.
 * Field `value`s are raw BibTeX field text (not the de-TeXified display form).
 */
export type EditCommand =
  | { readonly kind: 'setField'; readonly itemId: ItemId; readonly field: string; readonly value: string }
  | { readonly kind: 'removeField'; readonly itemId: ItemId; readonly field: string }
  | { readonly kind: 'setCiteKey'; readonly itemId: ItemId; readonly citeKey: string }
  | { readonly kind: 'setType'; readonly itemId: ItemId; readonly entryType: string }
  | { readonly kind: 'generateCiteKey'; readonly itemId: ItemId }
  | { readonly kind: 'addEntry'; readonly entryType: string; readonly crossref?: string }
  | { readonly kind: 'duplicateEntry'; readonly itemId: ItemId }
  | { readonly kind: 'deleteEntry'; readonly itemId: ItemId }
  | { readonly kind: 'mergeEntries'; readonly primaryId: ItemId; readonly otherIds: readonly ItemId[] }
  | { readonly kind: 'setMacro'; readonly name: string; readonly value: string }
  | { readonly kind: 'removeMacro'; readonly name: string };

/** Request to apply one {@link EditCommand} to a document. */
export interface ApplyEditRequest {
  readonly documentId: DocumentId;
  readonly command: EditCommand;
}

/** A bulk operation applied to every selected item (one undo step). */
export type BatchOp =
  | { readonly kind: 'setField'; readonly field: string; readonly value: string }
  | { readonly kind: 'addKeyword'; readonly keyword: string }
  | { readonly kind: 'removeKeyword'; readonly keyword: string }
  | { readonly kind: 'delete' };

/** Apply a {@link BatchOp} to a set of items. */
export interface BatchEditRequest {
  readonly documentId: DocumentId;
  readonly itemIds: readonly ItemId[];
  readonly op: BatchOp;
}

/** Outcome of a batch edit: the new dirty state + how many items changed. */
export interface BatchEditResult {
  readonly dirty: boolean;
  readonly count: number;
}

/** Outcome of an edit: the new dirty state and (when relevant) the affected item. */
export interface EditResult {
  readonly dirty: boolean;
  /** Item the edit focused on (for re-selection); absent for deletes/macros. */
  readonly affectedItemId?: ItemId;
  /** Refreshed detail of the affected item, when one applies. */
  readonly detail?: ItemDetail;
}

/** A document-level `@string` macro definition. */
export interface MacroDef {
  readonly name: string;
  /** Raw BibTeX value text (literal or `a # b` concatenation). */
  readonly value: string;
}

/** Request to list a document's `@string` macros. */
export interface ListMacrosRequest {
  readonly documentId: DocumentId;
}

/** A document's file-level macros, in dependency order. */
export interface ListMacrosResponse {
  readonly macros: readonly MacroDef[];
}

/** Request to save a document (optionally to a new path = Save As). */
export interface SaveDocumentRequest {
  readonly documentId: DocumentId;
  readonly targetPath?: string;
}

/** Result of a save: where it was written. */
export interface SaveDocumentResult {
  readonly documentId: DocumentId;
  readonly path: string;
  /** True if the user cancelled at the lossy-encoding prompt (nothing was written). */
  readonly cancelled?: boolean;
}

// --- Formatted citations (CSL) ----------------------------------------------

/** A selectable CSL citation style. */
export interface CitationStyle {
  readonly id: string;
  readonly label: string;
  /** True for a user-installed CSL style (removable in Preferences); bundled styles omit it. */
  readonly custom?: boolean;
}

/** The CSL styles the app offers (bundled offline by citation-js plugin-csl). */
export const CITATION_STYLES: readonly CitationStyle[] = [
  { id: 'apa', label: 'APA' },
  { id: 'vancouver', label: 'Vancouver' },
  { id: 'harvard1', label: 'Harvard' },
];

/** Request to format one item as a styled citation. */
export interface FormatCitationRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
  /** CSL style id from {@link CITATION_STYLES}. */
  readonly styleId: string;
}

/** Copy one item's formatted citation to the clipboard as RTF (+ plain text). */
export interface CopyRtfRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
  readonly styleId: string;
}

/** Result of a clipboard write. */
export interface CopyRtfResponse {
  readonly ok: boolean;
  readonly error?: string;
}

/** List bundled + user-installed CSL styles (for the Preferences picker). */
export type ListCitationStylesRequest = Record<string, never>;
export interface ListCitationStylesResponse {
  readonly styles: readonly CitationStyle[];
}

/** Install a `.csl` file the user picks (opens a file dialog in the main process). */
export type InstallCitationStyleRequest = Record<string, never>;
export interface InstallCitationStyleResponse {
  /** The newly installed style; undefined if the user cancelled the dialog. */
  readonly style?: CitationStyle;
  /** Set when the chosen file was not a valid CSL style. */
  readonly error?: string;
}

/** Remove a user-installed CSL style by id (bundled styles cannot be removed). */
export interface RemoveCitationStyleRequest {
  readonly id: string;
}
export interface RemoveCitationStyleResponse {
  readonly ok: boolean;
}

/**
 * Render a LaTeX/BibTeX preview of the bibliography by spawning the user's local
 * TeX toolchain (opt-in power-user feature; needs a TeX install). The artifact is
 * delivered back to the renderer's bottom panel: a small selection comes back as
 * inline SVG (DVI→dvisvgm), the whole library as PDF bytes (rendered with PDF.js).
 */
export interface TexPreviewRequest {
  readonly documentId: DocumentId;
  /** Which entries to typeset: the current selection, or the whole library. */
  readonly scope: 'selection' | 'library';
  /** Cite keys to include when `scope === 'selection'`. */
  readonly citeKeys?: readonly string[];
}
export interface TexPreviewResponse {
  readonly ok: boolean;
  /** Which artifact came back: themeable inline SVG, or PDF bytes for PDF.js. */
  readonly kind?: 'svg' | 'pdf';
  /** Inline SVG strings, one per page, when `kind === 'svg'`. */
  readonly svgs?: readonly string[];
  /** Raw PDF bytes (passed over IPC, not a path) when `kind === 'pdf'`. */
  readonly pdfBytes?: Uint8Array;
  /** Short failure reason (+ a log tail) on error: no TeX found, or a compile failure. */
  readonly error?: string;
}

/** Request the journal cover thumbnail for an item (resolved by ISSN/journal name). */
export interface JournalCoverRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
}

/** A journal cover: image bytes (null if none found) + how it was sourced + the journal name. */
export interface JournalCoverResponse {
  readonly data: Uint8Array | null;
  /** `og:image`/`twitter:image` ≈ real art; `favicon`/`apple-touch-icon` ≈ a logo. */
  readonly kind?: string;
  /** The journal name (for a generated fallback cover when `data` is null). */
  readonly journal?: string;
}

/** Attach a user-provided cover image to an item's journal (drag-drop onto the cover). */
export interface SetJournalCoverRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
  /** Already-downsized image bytes (the renderer resizes before sending). */
  readonly data: Uint8Array;
  /** File extension without the dot (jpg/png/…). */
  readonly ext: string;
}

/** Result of saving a user cover. */
export interface SetJournalCoverResponse {
  readonly ok: boolean;
  /** The journal the cover was attached to (for feedback). */
  readonly journal?: string;
}

/** Scan the open library for journals lacking a cover and propose Wikipedia downloads. */
export interface ScanJournalCoversRequest {
  readonly documentId: DocumentId;
}

/** One proposed cover from the scan, shown for review before saving. */
export interface JournalCoverProposal {
  readonly journal: string;
  readonly issn?: string;
  readonly data: Uint8Array;
  readonly ext: string;
  readonly sourceUrl: string;
  readonly wikiTitle: string;
}

/** Result of a journal-cover scan: proposals (with image bytes) for review. */
export interface ScanJournalCoversResponse {
  readonly proposals: readonly JournalCoverProposal[];
  /** How many distinct journals had no cover (the search space). */
  readonly missing: number;
  /** True if the scan stopped at a cap (so it didn't try every missing journal). */
  readonly capped?: boolean;
}

/** A user-approved cover to persist (subset of the scan proposals). */
export interface JournalCoverToSave {
  readonly journal: string;
  readonly issn?: string;
  readonly data: Uint8Array;
  readonly ext: string;
  readonly sourceUrl?: string;
  readonly wikiTitle?: string;
}

/** Persist the approved subset of scanned covers (documentId scopes the refresh). */
export interface SaveJournalCoversRequest {
  readonly documentId: DocumentId;
  readonly covers: readonly JournalCoverToSave[];
}

/** Result: how many covers were written. */
export interface SaveJournalCoversResponse {
  readonly saved: number;
}

/** Result: the formatted citation as an HTML string. */
export interface FormatCitationResult {
  readonly styleId: string;
  /** Formatted bibliography entry (HTML); empty when formatting failed. */
  readonly html: string;
  /** Failure reason when `html` is empty. */
  readonly error?: string;
}

// --- List publications ------------------------------------------------------

/** Sort direction for a publications listing. */
export type SortDirection = 'asc' | 'desc';

/**
 * One sort key + direction. A listing's sort is an ordered list of these
 * (primary first, then tie-breakers). `key` is a {@link PublicationRow} column
 * key (or any BibTeX field name the main process knows how to sort by); main
 * does the actual sorting using the core comparators.
 */
export interface SortSpec {
  readonly key: string;
  readonly direction: SortDirection;
}

/** Request payload for a page/range of publications. */
export interface ListPublicationsRequest {
  readonly documentId: DocumentId;
  /** 0-based index of the first row to return. */
  readonly offset: number;
  /** Maximum number of rows to return. */
  readonly limit: number;
  /**
   * Optional sort keys in priority order (primary first, then tie-breakers).
   * Main applies a default (cite key asc) when omitted or empty.
   */
  readonly sort?: readonly SortSpec[];
  /** When present, restrict rows to members of this group (see {@link GroupNode}). */
  readonly groupId?: string;
  /** Extra (non-builtin) field names to include in each row's `extra` map. */
  readonly extraFields?: readonly string[];
}

/**
 * Thin row view-model for the virtualized publications table. Every field is a
 * display-ready string: `authorsDisplay` is already formatted (via the name
 * formatter) and `title` is already de-TeXified for display. The renderer never
 * re-formats these.
 */
export interface PublicationRow {
  /** Stable item id (row key + the id to pass to {@link GetItemDetailRequest}). */
  readonly id: ItemId;
  /** Cite key column. */
  readonly citeKey: string;
  /** BibTeX entry type, lowercased (e.g. `article`, `book`). */
  readonly type: string;
  /** Authors column — pre-formatted display string (may be empty). */
  readonly authorsDisplay: string;
  /** Title column — de-TeXified for display (may be empty). */
  readonly title: string;
  /** Year column — display string (may be empty when absent/unparseable). */
  readonly year: string;
  /** True when the entry has a non-empty `Keywords` field (key-icon column). */
  readonly hasKeywords: boolean;
  /** True when the entry has a non-empty annotation (`Annote`); note-icon column. */
  readonly hasAnnotation: boolean;
  /** Number of local file attachments (`Bdsk-File-N` + `Local-Url`); paperclip column. */
  readonly attachmentCount: number;
  /** Tri-state of the `Read` boolean field: 1 on, -1 off, 0 unset (checkbox column). */
  readonly read: -1 | 0 | 1;
  /** Rating field value 0–5, or 0 when absent (star column). */
  readonly rating: number;
  /** Color-label swatch as a CSS `#rrggbb`, or undefined when no `Bdsk-Color`. */
  readonly color?: string;
  /** Display values for any user-configured extra-field columns (de-TeXified). */
  readonly extra?: Readonly<Record<string, string>>;
}

/** Set or clear the color label on a set of entries (`colorIndex` null/0 clears). */
export interface SetColorRequest {
  readonly documentId: DocumentId;
  readonly itemIds: readonly ItemId[];
  /** 1-based palette index (1..7), or null/0 to clear the color. */
  readonly colorIndex: number | null;
}

/** Result of {@link SetColorRequest}: how many entries were updated. */
export interface SetColorResponse {
  readonly count: number;
}

/** Response payload for a publications listing. */
export interface ListPublicationsResponse {
  /** The requested window of rows. */
  readonly rows: readonly PublicationRow[];
  /** Total number of rows in the (filtered) result set, for the virtualizer. */
  readonly total: number;
}

// --- List groups ------------------------------------------------------------

/**
 * Kind of group, mirroring BibDesk's taxonomy (subsystem-04). `library` is the
 * whole library; `static`/`smart` are user groups; `category`/`author` are
 * auto-generated field groups (author = person category field); `url`/`script`
 * are external groups. Read-only viewer renders all of them; only membership is
 * exercised.
 */
export type GroupKind =
  | 'library'
  | 'static'
  | 'smart'
  | 'category'
  | 'author'
  | 'url'
  | 'script'
  | 'folder';

/** Request payload for the groups sidebar tree. */
export interface ListGroupsRequest {
  readonly documentId: DocumentId;
}

/**
 * One node in the groups sidebar. The tree is reconstructed from `parentId`
 * (root parents have no `parentId`); BibDesk's tree is at most two levels deep.
 */
export interface GroupNode {
  /** Stable group id (pass as {@link ListPublicationsRequest.groupId}). */
  readonly id: string;
  /** Group kind — drives the sidebar icon. */
  readonly kind: GroupKind;
  /** Display name (de-TeXified / formatted by main as appropriate). */
  readonly name: string;
  /** Number of publications in the group (`library` = whole library size). */
  readonly count: number;
  /** Parent group id; absent for the fixed root parent groups. */
  readonly parentId?: string;
}

/** Response payload for the groups sidebar — a flat list joined via `parentId`. */
export interface ListGroupsResponse {
  readonly groups: readonly GroupNode[];
}

// --- Item detail ------------------------------------------------------------

/** Request payload for one item's full detail. */
export interface GetItemDetailRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
}

/**
 * Render the multi-select panels for a 2+ row selection: the detail pane (a list
 * of each entry's BibTeX preview + batch tools) and the bottom pane (each entry's
 * annotation). Main caps the rendered list; the response reports the full `count`.
 */
export interface RenderMultiPanelRequest {
  readonly documentId: DocumentId;
  /** Every selected item, in selection order (main caps how many it renders). */
  readonly itemIds: readonly ItemId[];
}
export interface RenderMultiPanelResponse {
  /** Total number of selected items (may exceed the number rendered into the list). */
  readonly count: number;
  /** Multi-select details-pane HTML (undefined on a template error). */
  readonly detailsHtml?: string;
  /** Multi-select bottom-pane HTML (undefined on a template error). */
  readonly bottomHtml?: string;
}

/** One field row in the detail view (display value, not raw BibTeX). */
/**
 * Field-type hint so the renderer can show the right editor widget. Classified by
 * the TypeManager (`rating`/`boolean`/`triState`/`person`/`citation`/`url`) with
 * everything else `plain` (a text input).
 */
export type FieldKind = 'plain' | 'person' | 'rating' | 'boolean' | 'triState' | 'url' | 'citation' | 'keywords';

export interface ItemField {
  /** Canonical field name (e.g. `Author`, `Title`, `Journal`). */
  readonly name: string;
  /** Display-ready value (macros expanded, de-TeXified by main). */
  readonly value: string;
  /** Raw BibTeX field text for editing (not de-TeXified / not brace-stripped). */
  readonly rawValue: string;
  /** True when the value is inherited from a crossref parent rather than set locally. */
  readonly isInherited: boolean;
  /** Editor-widget hint (see {@link FieldKind}); absent = `plain`. */
  readonly kind?: FieldKind;
  /** True when the field is required for the entry's type (must not be deletable). */
  readonly required?: boolean;
}

/** One attachment (linked file or remote URL) in the detail view. */
export interface ItemFile {
  /** `file` for a local file, `url` for a remote URL. */
  readonly kind: 'file' | 'url';
  /** Display name (basename for files, label/host for URLs). */
  readonly displayName: string;
  /** Resolved URL string (`file://...`/absolute path for local files, absolute URL otherwise). */
  readonly url: string;
  /**
   * Source `Bdsk-File-N` field name when this attachment is a removable managed
   * file link. Absent for attachments synthesised from `Url`/`Local-Url` fields.
   */
  readonly field?: string;
}

/** Request to add attachment(s) to an item. With `paths`, attaches those files
 * directly (drag-and-drop); without them, the main process opens a file picker. */
export interface AddAttachmentRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
  /** Absolute file paths to attach. When omitted/empty, main opens a picker. */
  readonly paths?: readonly string[];
}

/** Request to remove one managed attachment (`Bdsk-File-N`) from an item. */
export interface RemoveAttachmentRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
  readonly field: string;
}

/** A file attachment whose target is missing on disk (see {@link FindBrokenLinksResponse}). */
export interface BrokenLink {
  readonly itemId: ItemId;
  readonly citeKey: string;
  /** The attachment's display name (file basename). */
  readonly displayName: string;
  /** The resolved absolute path that does not exist. */
  readonly path: string;
  /** The `Bdsk-File-N` field, when this is a managed attachment (relocatable/removable). */
  readonly field?: string;
}

/** Request to scan a document for broken file links. */
export interface FindBrokenLinksRequest {
  readonly documentId: DocumentId;
}

/** All broken file links found in a document. */
export interface FindBrokenLinksResponse {
  readonly links: readonly BrokenLink[];
}

/**
 * Repair a broken managed attachment by pointing it at a file the user picks.
 * Main opens a file dialog; the chosen path is stored relative to the document.
 */
export interface RelocateAttachmentRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
  readonly field: string;
}

/** Request to read an attachment's bytes (e.g. to preview a PDF in-app). */
export interface ReadAttachmentRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
  /** The attachment's resolved url/path (from {@link ItemFile.url}). */
  readonly url: string;
}

/** Bytes of an attachment, or an error. `data` is structured-clone-safe. */
export interface ReadAttachmentResponse {
  readonly data: Uint8Array | null;
  readonly error?: string;
}

// --- Export -----------------------------------------------------------------

/**
 * Output format for {@link ExportTextRequest}. `bibtex` is implemented today
 * (reuses the round-trip serializer); the others are reserved for the export
 * feature and may be rejected with an error until then.
 */
export type ExportFormat = 'bibtex' | 'bibtex-minimal' | 'ris' | 'csv' | 'html' | 'rtf';

/** Request serialized text for a whole document, or a subset of its items. */
export interface ExportTextRequest {
  readonly documentId: DocumentId;
  readonly format: ExportFormat;
  /** When present, export only these items (in this order); else the whole library. */
  readonly itemIds?: readonly ItemId[];
}

/** Serialized text in the requested format, or an error if unsupported. */
export interface ExportTextResponse {
  readonly text: string;
  readonly error?: string;
}

/**
 * Print a formatted bibliography. Main renders the items as a CSL-formatted
 * HTML document and invokes the OS print dialog (which also offers Save as PDF).
 */
export interface PrintRequest {
  readonly documentId: DocumentId;
  /** Items to print, in order (e.g. the current group, or the multi-selection). */
  readonly itemIds: readonly ItemId[];
  /** CSL style id used to format each entry. */
  readonly styleId: string;
  /** Heading printed above the list (typically the document/group name). */
  readonly title: string;
}

/** Outcome of a print request; `ok` is true even if the user cancels the dialog. */
export interface PrintResponse {
  readonly ok: boolean;
  readonly error?: string;
}

/**
 * Export just the given entries (the current multi-selection) to a `.bib` file
 * the user picks. Complements whole-library {@link ExportTextRequest} export.
 */
export interface ExportSelectionRequest {
  readonly documentId: DocumentId;
  readonly itemIds: readonly ItemId[];
}

/** Outcome of an export-selection request; `ok` is true even if the user cancels. */
export interface ExportSelectionResponse {
  readonly ok: boolean;
  readonly error?: string;
}

// --- Online search / import -------------------------------------------------

/** An online bibliographic source. */
export type OnlineSource = 'crossref' | 'arxiv' | 'openalex' | 'pubmed' | 'doi' | 'isbn';

/** The online sources the app offers. */
export const ONLINE_SOURCES: readonly { id: OnlineSource; label: string }[] = [
  { id: 'crossref', label: 'CrossRef' },
  { id: 'openalex', label: 'OpenAlex' },
  { id: 'pubmed', label: 'PubMed' },
  { id: 'arxiv', label: 'arXiv' },
  { id: 'doi', label: 'DOI lookup' },
  { id: 'isbn', label: 'ISBN (book)' },
];

/** One normalised online search result (display fields + BibTeX fields to import). */
export interface OnlineResult {
  readonly source: OnlineSource;
  /** Suggested BibTeX entry type (e.g. `article`). */
  readonly entryType: string;
  readonly title: string;
  /** Display author list. */
  readonly authorsDisplay: string;
  readonly year: string;
  readonly venue?: string;
  readonly doi?: string;
  readonly url?: string;
  /** Canonical BibTeX fields used when importing this result as a new entry. */
  readonly fields: Readonly<Record<string, string>>;
}

/** Request to search an online source. */
export interface SearchOnlineRequest {
  readonly source: OnlineSource;
  readonly query: string;
}

/** Online search results (or an error message). */
export interface SearchOnlineResponse {
  readonly results: readonly OnlineResult[];
  readonly error?: string;
}

/** Request to import one online result into a document as a new entry. */
export interface ImportOnlineRequest {
  readonly documentId: DocumentId;
  readonly result: OnlineResult;
}

// --- Paste / drag-and-drop import -------------------------------------------

/** Paste BibTeX text into a document (e.g. an entry copied from Google Scholar). */
export interface PasteEntriesRequest {
  readonly documentId: DocumentId;
  /** Raw BibTeX text containing one or more `@type{…}` entries. */
  readonly text: string;
}

/** Import dropped files into a document: `.bib` merge, other files → entry+attach. */
export interface ImportFilesRequest {
  readonly documentId: DocumentId;
  /** Absolute file paths (from the renderer's drop handler). */
  readonly paths: readonly string[];
}

/** Open a file picker (in main) and import the chosen `.bib`/`.ris`/other files. */
export interface ImportDialogRequest {
  readonly documentId: DocumentId;
}

/** Outcome of a paste/file import: the new item ids and any non-fatal warnings. */
export interface ImportResult {
  readonly dirty: boolean;
  /** Ids of the newly added entries (for selection); empty when nothing imported. */
  readonly addedIds: readonly ItemId[];
  /** Non-fatal messages (e.g. "no entries found", per-file read errors). */
  readonly warnings: readonly string[];
}

// --- Find & Replace ---------------------------------------------------------

/** A find/replace operation over field values (preview when `apply` is false). */
export interface FindReplaceRequest {
  readonly documentId: DocumentId;
  /** Restrict to one field name, or undefined to search every field. */
  readonly field?: string;
  readonly find: string;
  readonly replace: string;
  /** Treat `find` as a JS regular expression. */
  readonly regex: boolean;
  readonly caseSensitive: boolean;
  /** When true, perform the replacement; when false, only report matches. */
  readonly apply: boolean;
  /** Restrict the scope to a group's members (optional). */
  readonly groupId?: string;
}

/** One field that matched (with the would-be/after value). */
export interface FindReplaceMatch {
  readonly itemId: ItemId;
  readonly citeKey: string;
  readonly field: string;
  readonly before: string;
  readonly after: string;
  /** Number of occurrences in this field. */
  readonly count: number;
}

/** Outcome of a find/replace: per-field matches and the running totals. */
export interface FindReplaceResult {
  readonly matches: readonly FindReplaceMatch[];
  /** Total number of occurrences across all matched fields. */
  readonly total: number;
  readonly applied: boolean;
  readonly dirty: boolean;
  /** Set when `find` is an invalid regular expression. */
  readonly error?: string;
}

// --- Group editor -----------------------------------------------------------

/** One smart-group condition (BibDesk BDSKCondition). */
export interface SmartCondition {
  readonly key: string;
  /** BDSKQueryOperator integer (e.g. contains/equals/starts-with). */
  readonly comparison: number;
  readonly value: string;
}

/** A mutation of the document's groups (create/rename/delete/membership). */
export type GroupCommand =
  | { readonly kind: 'createStatic'; readonly name: string; readonly citeKeys?: readonly string[] }
  | {
      readonly kind: 'createSmart';
      readonly name: string;
      readonly conditions: readonly SmartCondition[];
      /** 0 = all conditions (AND), 1 = any (OR). */
      readonly conjunction: 0 | 1;
    }
  | {
      readonly kind: 'editSmart';
      readonly groupId: string;
      readonly name: string;
      readonly conditions: readonly SmartCondition[];
      /** 0 = all conditions (AND), 1 = any (OR). */
      readonly conjunction: 0 | 1;
    }
  | { readonly kind: 'rename'; readonly groupId: string; readonly name: string }
  | { readonly kind: 'delete'; readonly groupId: string }
  | {
      readonly kind: 'setMembers';
      readonly groupId: string;
      readonly citeKeys: readonly string[];
      /** true = add to the static group, false = remove. */
      readonly add: boolean;
    }
  // --- folders (a folder contains other folders and/or groups) ---
  | { readonly kind: 'createFolder'; readonly name: string; readonly parentId?: string }
  | { readonly kind: 'renameFolder'; readonly folderId: string; readonly name: string }
  | { readonly kind: 'deleteFolder'; readonly folderId: string }
  /** Re-parent a folder (parentId omitted ⇒ top-level). */
  | { readonly kind: 'moveFolder'; readonly folderId: string; readonly parentId?: string }
  /** Place a group into a folder (folderId omitted ⇒ remove from any folder). */
  | { readonly kind: 'setGroupFolder'; readonly groupId: string; readonly folderId?: string };

/** Request to apply one {@link GroupCommand}. */
export interface GroupEditRequest {
  readonly documentId: DocumentId;
  readonly command: GroupCommand;
}

/** Outcome of a group edit: new dirty state + the affected/created group id. */
export interface GroupEditResult {
  readonly dirty: boolean;
  readonly groupId?: string;
}

/** Read back a smart group's editable definition (to populate the editor). */
export interface GroupConditionsRequest {
  readonly documentId: DocumentId;
  readonly groupId: string;
}

/** A smart group's current name, conjunction, and conditions. */
export interface GroupConditionsResponse {
  readonly name: string;
  /** 0 = all conditions (AND), 1 = any (OR). */
  readonly conjunction: 0 | 1;
  readonly conditions: readonly SmartCondition[];
}

/**
 * Rename an author/editor across every entry (also merges two name forms when
 * `newName` matches another existing author). Matching is by canonical name.
 */
export interface RenameAuthorRequest {
  readonly documentId: DocumentId;
  readonly oldName: string;
  readonly newName: string;
}

/** Outcome of an author rename: entries changed + new dirty state. */
export interface RenameAuthorResult {
  readonly changed: number;
  readonly dirty: boolean;
}

/** Open the standalone editor window for a single item. */
export interface OpenEditorRequest {
  readonly documentId: DocumentId;
  readonly itemId: ItemId;
}

/** Payload of the {@link IpcEvents.documentChanged} event (cross-window refresh). */
export interface DocumentChangedEvent {
  readonly documentId: DocumentId;
}

// --- Claude assistant -------------------------------------------------------

/** Whether the user's Anthropic API key is stored (via Electron safeStorage). */
export interface AgentKeyStatus {
  readonly hasKey: boolean;
  /** True if OS-level encryption is available for storing the key. */
  readonly encryptionAvailable: boolean;
}

/** Store (or, with an empty string, clear) the Anthropic API key. */
export interface AgentSetKeyRequest {
  readonly key: string;
}

/** Send one user message to the assistant for the open document. */
export interface AgentRunRequest {
  readonly documentId: DocumentId;
  readonly message: string;
}

/** The assistant's reply for one turn. */
export interface AgentRunResponse {
  readonly reply: string;
  /** Human-readable log of tool calls made this turn. */
  readonly toolLog: readonly string[];
  /** True if an approved mutation ran (the renderer should reload). */
  readonly mutated: boolean;
  readonly error?: string;
}

// --- AutoFile ---------------------------------------------------------------

/** AutoFile the managed attachments of one or more items into the Papers folder.
 * A multi-entry request is confirmed (and summarized) by the main process. */
export interface AutoFileRequest {
  readonly documentId: DocumentId;
  readonly itemIds: readonly ItemId[];
}

/** Result of an AutoFile: files moved, per-file errors, and (single-entry only)
 * the refreshed detail so the pane can update without a full reload. */
export interface AutoFileResult {
  readonly moved: number;
  readonly errors: readonly string[];
  readonly dirty: boolean;
  /** Present only for a single-entry AutoFile; bulk runs reload instead. */
  readonly detail?: ItemDetail;
}

/** Bulk AutoFile ("Consolidate Linked Files") — file every entry's attachments. */
export interface ConsolidateRequest {
  readonly documentId: DocumentId;
  /** When present and non-empty, file only these items; otherwise the whole library. */
  readonly itemIds?: readonly ItemId[];
}

/** Result of a Consolidate run: items scanned/affected, files moved, per-item errors. */
export interface ConsolidateResult {
  /** Items considered (library size, or the selection size). */
  readonly scanned: number;
  /** Items that had at least one file moved. */
  readonly itemsAffected: number;
  /** Total files moved across all items. */
  readonly moved: number;
  /** Whether the document now has unsaved changes. */
  readonly dirty: boolean;
  /** Per-file failures, each prefixed with the owning entry's cite key. */
  readonly errors: readonly string[];
}

/** Response from the folder picker (null when cancelled). */
export interface ChooseFolderResponse {
  readonly path: string | null;
}

// --- Field-value autocomplete -----------------------------------------------

/** Request distinct existing values for a field (for editor autocomplete). */
export interface FieldSuggestionsRequest {
  readonly documentId: DocumentId;
  readonly field: string;
}

/** Distinct values (deduped, sorted, capped) seen in the library for a field. */
export interface FieldSuggestionsResponse {
  readonly values: readonly string[];
}

// --- Find Duplicates --------------------------------------------------------

/** Request a duplicate scan of a document. */
export interface FindDuplicatesRequest {
  readonly documentId: DocumentId;
}

/** One entry within a duplicate group (light display info for the picker). */
export interface DuplicateEntry {
  readonly id: ItemId;
  readonly citeKey: string;
  readonly title: string;
}

/** A set of entries considered duplicates of one another. */
export interface DuplicateGroup {
  /** `citeKey` = identical cite keys; `content` = equivalent field content. */
  readonly kind: 'citeKey' | 'content';
  readonly entries: readonly DuplicateEntry[];
}

/** Result of a duplicate scan over a document. */
export interface FindDuplicatesResult {
  readonly groups: readonly DuplicateGroup[];
  /** Total number of entries involved in any duplicate group. */
  readonly total: number;
}

// --- Full-text search (SQLite FTS5) -----------------------------------------

/** Request a full-text search over a document. */
export interface FtsSearchRequest {
  readonly documentId: DocumentId;
  readonly query: string;
  /** Search extracted PDF body text too (full-text). Default false = fields only. */
  readonly includePdf?: boolean;
}

/** Full-text search results: matching item ids, best-match first. */
export interface FtsSearchResponse {
  /** False if the native FTS index is unavailable (caller should fall back). */
  readonly available: boolean;
  readonly ids: readonly ItemId[];
}

// --- Preferences ------------------------------------------------------------

/** User-overridable field-type classification sets (BibDesk's field-type prefs). */
export interface FieldTypeSettings {
  /** Fields holding people (parsed as authors). */
  readonly person: readonly string[];
  /** Local file-path fields. */
  readonly localFile: readonly string[];
  /** Remote URL fields. */
  readonly remoteURL: readonly string[];
  /** Star-rating (0–5) fields. */
  readonly rating: readonly string[];
  /** Boolean (checkbox) fields. */
  readonly boolean: readonly string[];
  /** Tri-state fields. */
  readonly triState: readonly string[];
  /** Citation (cite-key list) fields. */
  readonly citation: readonly string[];
}

/** A user-defined entry type's ordered required + optional field lists. */
export interface CustomEntryType {
  readonly required: readonly string[];
  readonly optional: readonly string[];
}

/**
 * User-defined entry types, keyed by type name. Matching is case-insensitive;
 * the 15 standard BibTeX types are protected and cannot be redefined here.
 */
export type CustomEntryTypes = Readonly<Record<string, CustomEntryType>>;

/** A user-authored export template: a Handlebars body + the output file extension. */
export interface ExportTemplate {
  readonly name: string;
  readonly extension: string;
  readonly body: string;
}

/**
 * A named, user-editable "fork" of a panel (detail-pane / bottom-panel) template:
 * a label the user picks + the Handlebars body. Forks are created by copying the
 * built-in default (or a preset), can be renamed/deleted, and one per panel can be
 * made the active template (see {@link Settings.activeDetailsFork}).
 */
export interface PanelTemplate {
  readonly name: string;
  readonly body: string;
}

/** Application preferences (persisted; the BibDesk-equivalent options this app has). */
export interface Settings {
  /** UI locale: `'system'` (follow the OS) or a code from `LOCALES` (e.g. `'fr'`). */
  readonly locale: string;
  /** UI theme. `system` follows the OS appearance. */
  readonly theme: 'light' | 'dark' | 'system';
  /** Default CSL style id for the citation preview (from {@link CITATION_STYLES}). */
  readonly defaultCiteStyle: string;
  /** Cite-key generation format (BDSKFormatParser mini-language, e.g. `%a1:%Y%u0`). */
  readonly citeKeyFormat: string;
  /**
   * How markdown annotations (the `Annote` "Notes" field) are written to the
   * `.bib`. `compressed` (default): lz-string→base64 in a private `Bdsk-Annotation`
   * field — brace-safe + compact, but opaque to other tools. `readable`: a
   * restricted `% { }` percent-escape in the standard `Annote` field — portable +
   * human-readable, but the flakier path. Reading handles both regardless.
   */
  readonly annotationStorage: 'compressed' | 'readable';
  /** Entry type used by the toolbar **New** button. */
  readonly defaultEntryType: string;
  /**
   * Template inserted when dragging rows to a TeX editor or copying `\cite{}`.
   * `%K` expands to the comma-joined cite key(s); e.g. `\cite{%K}`, `\citep{%K}`.
   */
  readonly citeCommandTemplate: string;
  /**
   * Ordered list of table column keys. Builtin keys: `citeKey`, `type`, `authors`,
   * `title`, `year`, `keywords`, `attachments`, `read`, `rating`. Any other key is
   * treated as a BibTeX field name and shown as a text column.
   */
  readonly columns: readonly string[];
  /**
   * Per-column width overrides in px, keyed by column id. A column absent here
   * uses its built-in default width (and, for Authors/Title, keeps growing to
   * fill); once a user drag-resizes a column it gets a fixed entry here.
   */
  readonly columnWidths: Record<string, number>;
  /** Absolute path of the AutoFile "Papers" folder (empty = AutoFile disabled). */
  readonly papersFolder: string;
  /** AutoFile destination-name format (BDSKFormatParser; default `%p1/%T5`). */
  readonly autoFileFormat: string;
  /** AutoFile an attachment automatically when it's added (needs a Papers folder). */
  readonly autoFileOnAdd: boolean;
  /** When true, save automatically a moment after each edit. */
  readonly autosave: boolean;
  /** When true, the filter box also searches extracted PDF body text (full-text). */
  readonly fullTextSearch: boolean;
  /** Max pages of each PDF to extract for the full-text index. 0 = the whole PDF
   * (use for long/scanned books); the default 40 keeps indexing fast for articles. */
  readonly ftsPageLimit: number;
  /** Anthropic model id for the Claude assistant (e.g. `claude-opus-4-8`). */
  readonly agentModel: string;
  /** BibTeX `.bst` style name for the LaTeX preview (e.g. `plain`, `abbrv`, `ieeetr`). */
  readonly texBibStyle: string;
  /**
   * Directory containing `pdflatex`/`bibtex`, when not on PATH (e.g.
   * `/Library/TeX/texbin`). Empty ⇒ search PATH + common install locations.
   */
  readonly texBinDir: string;
  /** Field-type classification overrides. */
  readonly fieldTypes: FieldTypeSettings;
  /** User-defined entry types (name → required/optional fields); standard types are protected. */
  readonly customTypes: CustomEntryTypes;
  /** User-authored export templates (named; listed under File → Export). */
  readonly exportTemplates: readonly ExportTemplate[];
  /** Resizable/hidable panel layout (persisted across sessions). */
  readonly layout: LayoutSettings;
  /** Named, editable forks of the detail-pane template (each copied from the default or a preset). */
  readonly detailsForks: readonly PanelTemplate[];
  /** Named, editable forks of the bottom-panel template. */
  readonly bottomForks: readonly PanelTemplate[];
  /** Name of the active detail-pane fork; absent/unknown ⇒ the built-in default. */
  readonly activeDetailsFork?: string;
  /** Name of the active bottom-panel fork; absent/unknown ⇒ the built-in default. */
  readonly activeBottomFork?: string;
  /**
   * @deprecated Migration-only. The pre-fork single override for the detail pane;
   * folded into a `detailsForks` entry on load (see `main/settings-migrate.ts`).
   */
  readonly detailsTemplate?: string;
  /**
   * @deprecated Migration-only. The pre-fork single override for the bottom panel;
   * folded into a `bottomForks` entry on load.
   */
  readonly bottomPanelTemplate?: string;
}

/** Persisted window-layout state: the resizable/hidable side and bottom panels. */
export interface LayoutSettings {
  /** Right (detail) pane width in px. */
  readonly rightPaneWidth: number;
  /** Whether the right pane is shown. */
  readonly rightPaneVisible: boolean;
  /** What the right pane shows: the detail view, or the Claude assistant. */
  readonly rightPaneContent: 'details' | 'assistant';
  /** Bottom panel height in px. */
  readonly bottomPanelHeight: number;
  /** Whether the bottom panel is shown. */
  readonly bottomPanelVisible: boolean;
  /** What the bottom panel shows: the entry annotation, or the LaTeX preview. */
  readonly bottomPaneContent: 'annotation' | 'texPreview';
}

/** Builtin (non-field) table column keys. */
export const BUILTIN_COLUMNS = [
  'citeKey',
  'type',
  'authors',
  'title',
  'year',
  'keywords',
  'attachments',
  'annotation',
  'read',
  'rating',
] as const;

/** Factory-default preferences (mirror the bundled BibDesk defaults). */
export const DEFAULT_SETTINGS: Settings = {
  locale: 'system',
  theme: 'system',
  defaultCiteStyle: 'apa',
  // Author-count-aware: Surname:Year (1 person), Surname1/Surname2:Year (2),
  // Surname1/etal:Year (3+). `%p` = authors, falling back to editors for entries
  // with no author (e.g. edited books). The `[/etal1]` trailing "1" caps shown
  // names at 1 once there are more than the requested 2. `%u0` appends a
  // disambiguating letter only on collision (…Yeara), unlike BibDesk's %u2 which
  // always appends two. See core/formats/src/author-count-format.test.ts.
  citeKeyFormat: '%p[/][/etal1]2:%Y%u0',
  annotationStorage: 'compressed',
  defaultEntryType: 'article',
  citeCommandTemplate: '\\cite{%K}',
  columns: ['citeKey', 'type', 'authors', 'title', 'year', 'keywords', 'attachments', 'read'],
  columnWidths: {},
  papersFolder: '',
  autoFileFormat: '%p1/%T5',
  autoFileOnAdd: false,
  autosave: false,
  fullTextSearch: false,
  ftsPageLimit: 40,
  agentModel: 'claude-opus-4-8',
  texBibStyle: 'plain',
  texBinDir: '',
  fieldTypes: {
    person: ['Author', 'Editor'],
    localFile: ['Local-Url'],
    remoteURL: ['Url', 'Doi', 'Citeseerurl'],
    rating: ['Rating'],
    boolean: ['Read'],
    triState: [],
    citation: ['Cited-By', 'Cites'],
  },
  customTypes: {},
  exportTemplates: [],
  detailsForks: [],
  bottomForks: [],
  layout: {
    rightPaneWidth: 340,
    rightPaneVisible: true,
    rightPaneContent: 'details',
    bottomPanelHeight: 200,
    bottomPanelVisible: false,
    bottomPaneContent: 'annotation',
  },
};

/** Request to read the current settings (no payload). */
export type GetSettingsRequest = Readonly<Record<string, never>>;

/** Request to update settings: a partial patch merged over the current values. */
export interface UpdateSettingsRequest {
  readonly patch: Partial<Settings>;
}

/** One entry type for the Preferences type editor and the type dropdowns. */
export interface EntryTypeInfo {
  readonly name: string;
  /** True for the 15 protected standard BibTeX types (read-only in the editor). */
  readonly standard: boolean;
  readonly required: readonly string[];
  readonly optional: readonly string[];
}

/** Response: every known entry type (standard + custom) with its field lists. */
export interface ListEntryTypesResponse {
  readonly types: readonly EntryTypeInfo[];
}

/** Request to select publications cited in a `.aux` file (main opens the picker). */
export interface SelectFromAuxRequest {
  readonly documentId: DocumentId;
}

/** Result of "Select Publications from .aux File": matched items + missing keys. */
export interface AuxSelectionResult {
  /** True when the user cancelled the file picker (no selection change). */
  readonly canceled: boolean;
  /** Item ids whose cite key was cited in the `.aux` (in `.aux` order). */
  readonly matchedIds: readonly string[];
  /** The cite keys that matched (parallel to {@link matchedIds}). */
  readonly matchedKeys: readonly string[];
  /** Cited cite keys not present in this library. */
  readonly missingKeys: readonly string[];
}

/** Request to export a folder's group→PDF directory tree to disk (main picks the dest). */
export interface ExportFolderTreeRequest {
  readonly documentId: DocumentId;
  readonly folderId: string;
}

/** Result of an "Export Folder to PDF Tree" run. */
export interface ExportFolderTreeResponse {
  /** True when the user cancelled the destination picker. */
  readonly canceled: boolean;
  /** Number of attachment files copied. */
  readonly copied: number;
  /** Per-file failures (each prefixed with the file name). */
  readonly errors: readonly string[];
}

/** Request to find publications missing a required field for their type. */
export interface SelectIncompleteRequest {
  readonly documentId: DocumentId;
}

/** Result: item ids of publications missing at least one required field. */
export interface SelectIncompleteResponse {
  readonly itemIds: readonly string[];
}

/** Request a live render of a Handlebars template body (for the editor preview). */
export interface PreviewTemplateRequest {
  readonly documentId: DocumentId;
  readonly body: string;
}

/** Result of a template preview render: the output text, or a compile/render error. */
export interface PreviewTemplateResponse {
  readonly text?: string;
  readonly error?: string;
}

/** Live render of a panel (detail/bottom) template body against a sample item. */
export interface PreviewPanelRequest {
  readonly documentId: DocumentId;
  /** Item to render against; omitted ⇒ the first item in the library. */
  readonly itemId?: ItemId;
  /** Which panel — picks the built-in default to preview when `body` is empty. */
  readonly which: 'details' | 'bottom';
  /** The template body to preview; empty ⇒ preview the built-in default. */
  readonly body: string;
}

/** Result of a panel preview render: the output HTML, or a compile/render error. */
export interface PreviewPanelResponse {
  readonly html?: string;
  readonly error?: string;
}

/**
 * Which entries a template export covers: the whole library (file order), the
 * entries currently shown (current group + search filter, in display order), or
 * the current multi-selection (in display order).
 */
export type TemplateExportScope = 'library' | 'shown' | 'selected';

/**
 * Menu → renderer request to export a named template at a given scope. The
 * renderer resolves `scope` to the concrete `itemIds` (it owns the selection and
 * the filtered/sorted view) and then calls {@link IpcChannels.exportTemplate}.
 */
export interface ExportTemplateMenuRequest {
  readonly templateName: string;
  readonly scope: TemplateExportScope;
}

/** Request to export a named template; `itemIds` (in order) scopes + orders it. */
export interface ExportTemplateRequest {
  readonly documentId: DocumentId;
  readonly templateName: string;
  /** Items to render, in order. Omitted ⇒ the whole library in file order. */
  readonly itemIds?: readonly ItemId[];
}

/** Result of a template export: written, cancelled at the save dialog, or errored. */
export interface ExportTemplateResponse {
  readonly ok?: boolean;
  readonly canceled?: boolean;
  readonly error?: string;
}

/**
 * Full detail of one publication for the detail/preview pane. `fields` are the
 * display field rows, `files` the attachments, and `previewHtml` an optional
 * pre-rendered HTML snippet for the preview card (rendered by main from a
 * template). The renderer treats `previewHtml` as trusted-but-sanitized content.
 */
export interface ItemDetail {
  readonly id: ItemId;
  readonly citeKey: string;
  /** BibTeX entry type, lowercased. */
  readonly type: string;
  readonly fields: readonly ItemField[];
  readonly files: readonly ItemFile[];
  /** Optional pre-rendered HTML for the preview card. */
  readonly previewHtml?: string;
  /** Raw markdown notes (the `Annote` field) for the notes editor. */
  readonly notesRaw: string;
  /** Rendered notes HTML (markdown + `[[citeKey]]` cross-references). */
  readonly notesHtml: string;
  /**
   * The detail pane rendered as HTML from the (default or user) Handlebars
   * template + `bd-*` web components. The renderer drops this into the pane and
   * hydrates it; absent ⇒ the renderer falls back to its legacy React composition.
   */
  readonly detailsPanelHtml?: string;
  /** The bottom panel rendered as HTML (default = the annotation reader). */
  readonly bottomPanelHtml?: string;
}

// --- Menu commands ----------------------------------------------------------

/**
 * A renderer-side action triggered from the native application menu. Main owns
 * the menu (an Electron requirement) but most items act on renderer/store state
 * (selection, modals, theme), so it forwards them as one of these commands via
 * the {@link IpcEvents.menuCommand} event; the renderer dispatches to the store.
 *
 * File-level actions that main can do itself (Open, Save, Save As, Revert,
 * Export to a file) are handled in main directly and are NOT in this union.
 */
export type MenuCommand =
  // Publication
  | 'newPublication'
  | 'pastePublication'
  | 'importFile'
  | 'editEntry'
  | 'duplicate'
  | 'delete'
  | 'generateCiteKey'
  | 'newWithCrossref'
  | 'selectParent'
  | 'addAttachment'
  | 'autoFile'
  | 'consolidate'
  | 'selectFromAux'
  | 'online'
  | 'editMacros'
  | 'findDuplicates'
  | 'findBrokenLinks'
  | 'scanJournalCovers'
  | 'texPreview'
  | 'assistant'
  // Edit / clipboard (operate on the selection)
  | 'find'
  | 'findReplace'
  | 'selectIncomplete'
  | 'copyCiteKey'
  | 'copyCitation'
  | 'copyBibtex'
  | 'copyCite'
  | 'copyRtf'
  | 'copyRis'
  | 'copyMinimalBibtex'
  | 'copyBibitem'
  // View
  | 'toggleTheme'
  | 'toggleSidePanel'
  | 'toggleBottomPanel'
  | 'sidePaneDetails'
  | 'sidePaneAssistant'
  | 'bottomPaneAnnotation'
  | 'bottomPaneTexPreview'
  // App
  | 'save'
  | 'print'
  | 'exportSelected';
